### PR TITLE
LKE-9060: Add node-js-and-express dashboard

### PR DESCRIPTION
**Pull request by enys**

### CODE REVIEW

**Comment by enys** [comment]
@fantandrea I'm preparing documentation for https://linkurious.atlassian.net/browse/LKE-9060 are you the owner of this repo ?

**Comment by enys** [comment]
@Linkurious/solution-engineers This is needed for a documentation PR that I am trying to include in v4.0.7 out this week. 
I will merge this this afternoon if I don't have any news.

**Comment by fantandrea** [comment]
@enys I saw you were already working with @andre91a on that PR. Just be sure you properly mention this as well

**Comment by enys** [comment]
Not sure I understand what you mean.
That's why I pinged SE

**Pull request merged**
